### ISSUE TITLE
Create Basic React Pages

### ISSUE THREAD

**Issue by jwilferd10** [Siphon880gh/reprint#13]
### Create Skeletal Structure of React Pages
**Pages to be created:**
- About
- Favorites
- Profile

NOTE: These do not need to return data yet, they just need to exist. Once the pages work correctly and show hardcoded information, start moving to call appropriate data to show information from the database

**Comment by jwilferd10** [comment]
### Update 1.1:

Following has been added: 
- addPost.js
   - Barebones structure that showcases first draft of how the page will look
- Team.js added 
    - Basic  'Meet the team' design type page to showcase the people behind the project

**Comment by jwilferd10** [comment]
### Update 1.2:

**Consider using Ant Design or Chakra UI**

Two new pages to be worked on: 
- Author.js 
   - Think of author as another user's profile. 
- Reprint.js
   - Will be page where the reprint is showcased

**Comment by clhurlbut** [comment]
> ### Update 1.2:
> **Consider using Ant Design or Chakra UI**
> 
> Two new pages to be worked on:
> 
> * Author.js
>   
>   * Think of author as another user's profile.
> * Reprint.js
>   
>   * Will be page where the reprint is showcased

I made the profile page work for both the user or a different username. No need for the author page now

**Comment by Siphon880gh** [comment]
Great. You can use the useQuery hook to see if it's at /me, otherwise
that's the user id at the end.

**Comment by Siphon880gh** [comment]
useParam* hook from React Router

**Comment by jwilferd10** [comment]
### Update 1.3:
Majority of pages have been created, now need to be fleshed out. Issue should be done.
