### ISSUE TITLE
Modify Queries.js

### ISSUE THREAD

**Issue by jwilferd10** [Siphon880gh/reprint#16]
### Refactor current queries.js to export the appropriate data
- Set up a query for STREAM
- Set up a query for REPRINT_PAGE
- Refactor the GET_ME to call the appropriate data

**Comment by clhurlbut** [comment]
I have created a few more Queries, need to work on one for getting the favorites for the favorites page

**Comment by jwilferd10** [comment]
### Update:
Additional queries are being created, this issue will still be open as more modifications may happen in the future.

**Comment by jwilferd10** [comment]
### Update 1.1:
Queries are, for the most part, altered as much as it is needed. Small modifications may occur in the future, but the main modifications are otherwise complete. This issue is closed.
