### ISSUE TITLE
Add Search box

### ISSUE THREAD

**Issue by Siphon880gh** [Siphon880gh/reprint#3]
Please refer to screenshot to see where we should have the searchbar. Thanks.

<img width="302" alt="Screen Shot 2021-03-28 at 5 26 29 PM" src="https://user-images.githubusercontent.com/5465445/112781104-0c41bf80-8fff-11eb-8bd2-a40855c61e49.png">

Refer to this screenshot from Nifty to see how we want the results to be implemented. The two sections should be Users and Reprints though:
<img width="512" alt="Screen Shot 2021-03-28 at 7 54 55 PM" src="https://user-images.githubusercontent.com/5465445/112781361-81ad9000-8fff-11eb-82d2-144b6a9f26aa.png">

Thanks!

**Comment by clhurlbut** [comment]
added the search bar, need to add functionality
